apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deploy
  labels:
    app: myjavaapp
spec: 
  replicas: 3
  selector: 
    matchLabels: 
     app: myjavaapp
  template:
    metadata:
     labels:
       app: javaapp
    spec:
     containers:
     - name: myjavaapp-container
       image: maha4iac/myonlinebooking:2
       ports:
       _ containerPort: 8080