apiVersion: v1
kind: ReplicationController
metadata: 
  name: myjavaapp-rc
spec:
  replicas: 5
  selector:
    app: myjavaapp
  template:
    metadata: 
      labels:
        app: myjavaapp
    spec: 
      container:
      - name: mycontainer
        image: maha4iac/mymahaapp:1
        ports:
        - containerPort:8080