apiVersion: v1
kind: Service
metadata: 
  name: venu-svc
  labels: 
    app: myjavaapp
    version: 2.6.2
spec:
    type: nodePort:
    ports:
    - port: 8080
      nodePort: 30001
      protocol: TCP
    selector:
      app: myjavaapp
      version: 2.6.2

